spring:
  profiles.active: dev
---
spring:
  profiles: dev
entitymanager.packagesToScan: ua.batimyk.vrentalstore

database:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://aa1bi1ok0629fjj.c7reurckgtex.eu-central-1.rds.amazonaws.com:3306/sakila
  username: sakila
  password: sakila

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl.auto: validate

facebook:
  client:
    clientId: 233668646673605
    clientSecret: 33b17e044ee6a4fa383f46ec6e28ea1d
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

logging:
  level:
    org.springframework.web: ERROR
    org.hibernate: DEBUG
    org.springframework.security: ERROR
---
spring:
  profiles: prod

entitymanager.packagesToScan: ua.batimyk.vrentalstore

server:
  port: 5000

database:
  driverClassName: com.mysql.jdbc.Driver
  url: jdbc:mysql://aa1bi1ok0629fjj.c7reurckgtex.eu-central-1.rds.amazonaws.com:3306/sakila
  username: sakila
  password: sakila

hibernate:
  dialect: org.hibernate.dialect.MySQL5Dialect
  show_sql: true
  hbm2ddl.auto: validate

facebook:
  client:
    clientId: 1352677998099673
    clientSecret: 0115cc748760ce7c9d9d6d9216d62f3c
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me

logging:
  level:
    org.springframework.web: ERROR
    org.hibernate: ERROR
    org.springframework.security: ERROR